### ISSUE TITLE
not able to use postback response

### ISSUE THREAD

**Issue by deepak-kumar-sinha** [crazymeeks/dragonpay#1]
Is there any function which can be use after successful payment???
Means if payment got successful then its should be redirect to some specific URL

**Comment by crazymeeks** [comment]
Hi @deeprajsinha , this is not handled by the library, you need to give your return url to Dragonpay and have them set. Dragonpay will handle the redirection.

**Comment by crazymeeks** [comment]
This is not an issue. Closing this
