### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by sironronron** [crazymeeks/dragonpay#10]
I'm using Laravel 6.* as my backend and vuejs axios for my frontend

I'm getting 

`Access to XMLHttpRequest at 'http://127.0.0.1:8000/api/v1/subscription/payment/dragonpay' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. `

when I use SOAP/XML Web Service Model.

**Comment by crazymeeks** [comment]
Hi,

I would love to help you but this error has nothing to do with the library. You need to set the CORS policy on the application or server level. Closing this ticket now.
