### ISSUE TITLE
Invalid Token Error

### ISSUE THREAD

**Issue by SyKenneth** [crazymeeks/dragonpay#13]
We recently got an Invalid Token Error using the SOAP/XML method. But when we updated the production url from  https://secure.dragonpay.ph to https://gw.dragonpay.ph, it started to work again. Dragonpay probably changed something in their side.

**Comment by crazymeeks** [comment]
Hi @SyKenneth, how do you ended up with the url https://secure.dragonpay.ph? I don’t even have this url in my code.

**Comment by SyKenneth** [comment]
It is located on line 154 of src/Foundation/PaymentGateway/Dragonpay.php

**Comment by crazymeeks** [comment]
@SyKenneth, I see! maybe typo error on my end. Will fix on the next patch. Thanks for reporting

**Comment by crazymeeks** [comment]
This issue is now fix. please use latest release **v3.2.8**. Click [here](https://github.com/crazymeeks/dragonpay/wiki/v3.2.8) for documentation. Thank you for reporting! Closing this issue now!
