### ISSUE TITLE
CheckTransactionStatus not working

### ISSUE THREAD

**Issue by bernie-lorbis** [crazymeeks/dragonpay#15]
ERROR MESSAGE: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. Please review the following URL and make sure that it is spelled correctly.

use Crazymeeks\Foundation\PaymentGateway\DragonPay\Action\CheckTransactionStatus;

**Comment by crazymeeks** [comment]
Hi @p-blorbis ,

The endpoint provided by Dragonpay prior to their release of version 1.03 on March 3, 2019 has stopped working.
For now, you can check their updated doc [here](https://www.dragonpay.ph/wp-content/uploads/2018/05/Dragonpay-PS-API.pdf) at page 5.3.1 while I'm fixing this issue.

**Comment by crazymeeks** [comment]
Hi @p-blorbis ,

Updated this library. Please use version v3.2.10. This should fix your problem. Refer to the docs also as I updated the doc. Please make sure to hard refresh to make sure you get the updated docs.

**Comment by bernie-lorbis** [comment]
Thanks, its working now
<img width="664" alt="Screen Shot 2022-05-19 at 8 40 46 PM" src="https://user-images.githubusercontent.com/69284821/169295800-00c15c0a-ed33-4564-9aa7-0a1389369fb5.png">
