### ISSUE TITLE
Where is procid?

### ISSUE THREAD

**Issue by eureckou** [crazymeeks/dragonpay#2]
I apologize if this is more of a request and not an issue but anyways I was using your code before and also procid was missing. I was hoping you'll include it in this release but did not. I was wondering why?

Here's an excerpt from Dragonpay PS doc for reference "to give user the capability to go straight to that channel without stopping by the Dragonpay payment selection page by passing a “procid” parameter".

**Comment by crazymeeks** [comment]
@eureckou, Thanks! will include this in the next 3.1.0 release!

**Comment by crazymeeks** [comment]
@eureckou , "procid" was added in v3.1.0. Just import Crazymeeks\Foundation\PaymentGateway\Options\Processor class.
Options available:
Processor::GCASH
Processor::CREDIT_CARD
Processor::PAYPAL

Example Usage:
$dragonpay = new Dragonpay();
$dragonpay->setParameters($parameters)
                  ->withProcid(Processor::CREDIT_CARD)->away();

**Comment by eureckou** [comment]
Thanks for taking time with the procid but I was really hoping to use Dragonpay Prepaid Credits. Can I just include Processor::DPAY? 

Edit: I just added DPAY in Processor.php and it worked like a charm. Thanks!

**Comment by crazymeeks** [comment]
@eureckou , You can also contribute to this library. I am more than happy if you do 👍 
BTW , instead of editing directly the source code, you can add additional parameters like below:
$dragonpay->parameters->add([‘name’ => ‘value’]);
