### ISSUE TITLE
CheckStatus seems to be not working using sandbox. Returns unknown even if transaction exist

### ISSUE THREAD

**Issue by Victor1224** [crazymeeks/dragonpay#3]
Below is my current code
$txnid = xxxxxxxx;
$merchant_account = [
    'merchantid' => 'xxxx',
    'password'   => 'xxxx',
];
$dragonpay = new Dragonpay($merchant_account);
$status         = $dragonpay->action(new CheckTransactionStatus($txnid));

dd(var_dump($status)); => returns "unknown"

**Comment by crazymeeks** [comment]
Hi @Victor1224 , thanks for reporting. Will check this.

**Comment by Victor1224** [comment]
Thanks @crazymeeks, I appreciate the help. I tried dragonpay API to get status https://test.dragonpay.ph/MerchantRequest.aspx?op=GETSTATUS and seems to be working.

**Comment by crazymeeks** [comment]
Yes @Victor1224 , only the Soap web service seems not working but this is on the side of DP itself. BTW, it's already fixed. Just install **v3.2.1**. Your code will work as is.
Reference tag: https://github.com/crazymeeks/dragonpay/releases/tag/v3.2.1

**Comment by Victor1224** [comment]
Thanks @crazymeeks it's working now.. I appreciate the help. :)
