### ISSUE TITLE
URL encoded description on tokenized payment URLs?

### ISSUE THREAD

**Issue by NikkoJaca** [crazymeeks/dragonpay#8]
Hello.

I'm using v3.2.4 of this package.

Trying to test out your package, and I noticed when I try the tokenized URL method on post-checkout, the description is getting malformed, spaces are transforming into plus signs and special characters turning into gibberish.

Scrutinizing into the package's code, I found out that the `description` parameter is getting URL-encoded? Compared to non-tokenized URL, the description is not being URL-encoded.

Screenshot when using tokenized URL with BogusBank and passing the value `José Rizal` into `description`:

![Using BogusBank](https://user-images.githubusercontent.com/45310280/83381230-af8f6b80-a412-11ea-94c6-7854e0464b39.png)

[The line 166 at `src/Foundation/PaymentGateway/Parameters.php` file might be the cause?](https://github.com/crazymeeks/dragonpay/blob/da0b2b3651f5037d0da33bd83e8f786a5e645c68/src/Foundation/PaymentGateway/Parameters.php#L166)

Or there might be a reason why we need to URL-encode the `description` when using tokenized URLs?

Hoping for your positive feedback!

**Comment by crazymeeks** [comment]
Hi,

I'm gonna take a look at this and will create another release for this issue.

**Comment by crazymeeks** [comment]
Hi,

This issue had been fixed. You may use `v3.2.5.` Let me know this works for you so I can close this issue.

Thank you for reporting!

**Comment by NikkoJaca** [comment]
It works fine now, thank you for the patch!

**Comment by crazymeeks** [comment]
Closing this issue now.
