### ISSUE TITLE
Void/Cancellation of Payment always results to success/true even I supplied it with invalid transaction ID

### ISSUE THREAD

**Issue by NikkoJaca** [crazymeeks/dragonpay#9]
Hello. I'm using this package's version `v3.2.4` and using Laravel version `6.13.1`.

While trying to test out the void/cancellation of pending payments, I found a possible bug.

Using the following code snippet:
```PHP
 $dragonpay = new Dragonpay($merchant_account);
        try{
             $dragonpay->action(new \Crazymeeks\Foundation\PaymentGateway\Dragonpay\Action\CancelTransaction($txnid));
        }catch(\Crazymeeks\Foundation\Exceptions\Action\CancelTransactionException $e){
            return false;
        }
```

And noticed that even if I put anything in the `$txnid` variable, it returns `true` value.

Investigating further, the following condition [starting at line 56 of `src/Foundation/PaymentGateway/DragonPay/Action/CancelTransaction.php` file:](https://github.com/crazymeeks/dragonpay/blob/da0b2b3651f5037d0da33bd83e8f786a5e645c68/src/Foundation/PaymentGateway/DragonPay/Action/CancelTransaction.php#L56)

```PHP
$result = parent::doAction($dragonpay, $curl);

        if ($result == 0) {
            return true;
        }

        throw new CancelTransactionException();
```

evaluates the `$result == 0` to `true` even if the `$result` variable contains a webpage that shows the following:

![Image shows an error that is caused by wrong void payment URL](https://user-images.githubusercontent.com/45310280/83474005-85df4e80-a4bd-11ea-870d-7aa32a9f3629.png)
 
This webpage is caused by an invalid URL for payment void/cancellation, as I have observed during URL building [at line 51 of `/src/Foundation/PaymentGateway/DragonPay/Action/BaseAction.php` file.](https://github.com/crazymeeks/dragonpay/blob/da0b2b3651f5037d0da33bd83e8f786a5e645c68/src/Foundation/PaymentGateway/DragonPay/Action/BaseAction.php#L51)

When I tried to check the `$url` variable using dump and die function (`dd()`), the generated URL shows the following:

```
https://test.dragonpay.ph/Pay.aspx/MerchantRequest.aspx?op=VOID&merchantid=XXXX&merchantpwd=XXXXXXXXXXX&txnid=XXXXXXXX
```

There seems to be an extra `.../Pay.aspx/...` into the URL, which it shouldn't be there as per [Dragonpay's documentation](https://www.dragonpay.ph/wp-content/uploads/Dragonpay-PS-API-latest.pdf):

![Dragonpay documentation about Payment Cancellation/Void](https://user-images.githubusercontent.com/45310280/83474649-0fdbe700-a4bf-11ea-8c9d-6231b149dd2b.png)

I tried removing the `.../Pay.aspx/...` in the URL and was able to get a `0` (successful) value through the browser. The URL building seems to be reliant to the protected variable `$baseUrl`.

Hoping this would be fixed soon!

EDIT: grammar

**Comment by crazymeeks** [comment]
Hi,

Thank you for reporting this bug. I will release a new version once this issue is solved.

**Comment by crazymeeks** [comment]
Hi, 
This issue had been fixed. You may use `v3.2.5`. Let me know if it works for you so I can close this issue.

Thank you for reporting!

**Comment by NikkoJaca** [comment]
It works! Thanks for the update!

**Comment by crazymeeks** [comment]
Closing this ticket now.
